name: Update Top Contributors

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  push:
    branches:
      - main  # Or your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4  # Usa la versión más reciente que sea compatible con Node.js 20
    - name: Set up Python
      uses: actions/setup-python@v5.1.0  # Usa la versión más reciente según los releases
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Generate SVG badges
      run: python generate_top_contributors_svg.py
    - name: Update README
      run: |
        README_CONTENT="## Top Contributors\n"
        for i in {1..3}
        do
          SVG_CONTENT=$(cat top_$i.svg | base64 -w 0)
          README_CONTENT+="![Top $i](data:image/svg+xml;base64,$SVG_CONTENT) "
        done
        echo -e "$README_CONTENT" > README.md
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update Top Contributors badges"
        git push
